name: Build and deploy frontend and backend apps to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip apps from /dist
    steps:
      - name: Clean dist folder (optional but helps)
        run: rm -rf dist

      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build all apps
        run: npm run build

      - name: Zip data-api
        run: |
          cd dist/apps/data-api/
          zip -r ${{ github.workspace }}/data-api-release.zip .

      - name: Upload data-api artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-api
          path: data-api-release.zip

      - name: Zip my-app (Angular frontend)
        run: |
          cd dist/apps/my-app/
          zip -r ${{ github.workspace }}/my-app-release.zip .

      - name: Upload my-app artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: my-app-release.zip

      - name: Zip rcmnd-api
        run: |
          cd dist/apps/rcmnd-api/
          zip -r ${{ github.workspace }}/rcmnd-api-release.zip .

      - name: Upload rcmnd-api artifact
        uses: actions/upload-artifact@v4
        with:
          name: rcmnd-api
          path: rcmnd-api-release.zip

  deploy-my-app:
    runs-on: ubuntu-latest
    name: Deploy Angular Frontend
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-app

      - name: Unzip artifact
        run: unzip my-app-release.zip

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: /
          output_location: .

  deploy-data-api:
    runs-on: ubuntu-latest
    name: Deploy NestJs data-api backend
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: data-api

      - name: Unzip artifact
        run: unzip data-api-release.zip

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nx-games'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NESTJS_PUBLISHPROFILE }}
          package: .

  deploy-rcmnd-api:
    runs-on: ubuntu-latest
    name: Deploy rcmnd-api backend
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: rcmnd-api

      - name: Unzip artifact
        run: unzip rcmnd-api-release.zip

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nx-games-neo4j'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEO4J_PUBLISHPROFILE }}
          package: .
